# Problem Set 1
Variables, Strings, Numbers, and ArrayNumpy


## Variables, expression and statements

### Exercise 1
Write a program to prompt the user for hours and rate per hour to compute gross pay of a worker.

    Enter Hours: 35
    Enter Rate: 2.75
    Gross Pay: 96.25


In [ ]:
hrs = int(input("Enter hours: "))
rate = float(input("Enter Rate: "))
pay = hrs*rate

print("Gross pay: " + str(pay))


### Exercise 2
Assume that we execute the following assignment statements:

    width = 17
    height = 12.0
    
For each of the following expressions, write the value of the expression and the type (of the value of the expression).

    1. width//2 
    2. width/2.0 
    3. height/3 
    4. 1 + 2 * 5
    

In [13]:
w = 17
h = 12.0

one = w//2
print(one)


type(one)

8


int

In [14]:
two = w/2.0
print(two)
type(two)

8.5


float

In [15]:
three = h/3
print(three)
type(three)


4.0


float

In [16]:
four = 1+2*5
print(four)
type(four)


11


int

### Exercise 3
Please debug the following lines of Python code (ie: explain the error and fix it):

i)   6pack = "6"

ii)  can volume = 50

iii) class = "GRA4142"

iv)  ltr/fl.oz = 2.5

Note: Please feel free to google for answers

In [ ]:
sixpack = "6" #no numbers in variable name
sixpack

In [ ]:
can_volume = 50 #no space in variable name, use underscore
can_volume

In [ ]:
course = "GRA4142" #class is defined and can therefore not be used, use a diff variable name
course

In [ ]:
ltr_to_oz= 2.5
ltr_to_oz


### Exercise 4
Please write a piece of code to display the volume of a 6-pack of cans and the total volume of the 6-pack and a 2-liter bottle. (1 can = 0.355 liter) Please make some comments on the code you write.

In [ ]:
can = 0.355 #liters of fluid

sixpack = can*6 #6pack is cans (0.355) times 6
twoliter = 2  #2 liter bottle

total = sixpack + twoliter

print("A sixpack contains " + str(sixpack) + " liters")
print("A sixpack and a two liter bottle contains " + str(total) + " liters")


### Exercise 5
Please compute the following 

$\frac{2.4+5.6}{2}$

$\frac{2.4\times5.6}{2}$


$2\times\left(1+\frac{5}{100}\right)^{3}$

$\sqrt{(2^{2}+3^{2} )}$ 



In [ ]:
n1 = (24+5.6)/2
n1

In [ ]:
n2 = (2.4*5.6)/2
n2

In [ ]:
n3 = 2*(1+(5/100))**3
n3

In [6]:
import math 
n4 = math.sqrt((2**2+3**2))
n4

3.605551275463989

### Exercise 6
The volume of a sphere is given by

$V=\frac{4}{3}\pi r^{3}$ 

If the radius is given by a variable radius that contains a floating-point value, write a Python expression for the volume.

In [ ]:
import math
r = input("Radius (r): ")
r = float(r)
v = (4/3)*math.pi * (r**3)
v = str(v)
print("Volume of sphere is : " + v)

### Exercise 7
Compute the following

i) `1729 // 10` and

ii) `1729 % 10`

In [18]:
n1 = 1729 // 10 #floor division
n1

172

In [17]:
n2 = 1729 % 10 #modulus
n2

9



### Exercise 8

- Store your first name, in lowercase, in a variable.
- Using that one variable, print your name in lowercase, Titlecase, and UPPERCASE.
- Store your first name and last name in separate variables (`full_name`, for example), and then combine them to print out your full name.
- display the length of the `full_name`.
- Select your last name from `full_name`
- Display your full name three times in three lines.



In [19]:
fname = "oscar"
fname.lower() #lower

'oscar'

In [20]:
fname.title() #Title, first letter

'Oscar'

In [21]:
fname.upper() #all uppercase

'OSCAR'

In [26]:
lname = "dyremyhr"
full_name = fname + " "+ lname
full_name #full name

'oscar dyremyhr'

In [29]:
len(full_name)

14

In [28]:
full_name[6:] #from position 5 onwards

'dyremyhr'

In [30]:
for i in range(3): 
    print("My name is : " + full_name)

My name is : oscar dyremyhr
My name is : oscar dyremyhr
My name is : oscar dyremyhr


### Exercise 9
What does the following statement sequence print?

    string = "Harry"
    n = len(string)
    mystery = string[0] + string[n - 1] 
    print(mystery)

Please think before you run it.

In [ ]:
#it will print H + string (5-1) which is H + string(4) = Hy

In [31]:
string = "Harry"
n = len(string)
mystery = string[0] + string[n - 1] 
print(mystery)


Hy


### Exercise 10
Please write a piece of code to obtain two names from the user and prints a pair of initials.

In [41]:
fname = input("Enter your fname: ")
oname = input("Enter significant other's first name: ")
intial = fname[0] + "&" +oname[0]
print(inital.upper())

Enter your fname: osva
Enter significant other's first name: sd


### Exercise 11
What is the output of the following statement sequence?

    volume = 10
    print("The total volume is %5d" % volume)

In [34]:
v = 10
print("The total volume is %5d" % v) # 5 spaces


The total volume is    10


### Exercise 12
Generate a variable: 
    
    name = '\t\teric'
    
Please strip whitespace from strings.    

In [37]:
name = '\t\teric'
name.strip()



'eric'


### Exercise 13
There is a string method called count that is similar to
the function in the previous exercise. Read the documentation of this method at https://docs.python.org/3.5/library/stdtypes.html#string-methods and write an invocation that counts the number of times the letter a
occurs in “banana”.

In [4]:
string = 'banana'
string.count('a', 3, 6)



2

### Exercise 14

Gernate a variable of string: `Python`. Please find the position of the charatcter `o` in this string.

In [7]:
string = 'Python'
string.find('o')

4

### Exercise 15
Consider the following string
    
    s = '0123456789'

Do the following steps: 

1. Print the object
2. Show first element (in this case a letter)
3. Grab everything past the first term all the way to the length of s which is len(s)
4. Grab everything UP TO the 3rd index
5. Display everything
6. Display last letter (one index behind 0 so it loops back around)
7. Grab everything but the last letter
8. Grab everything, but go in steps size of 1
9. Grab everything, but go in step sizes of 2
10. Print the string backwards

In [11]:
s = '0123456789'
s

'0123456789'

In [12]:
s[0]

'0'

In [14]:
s[1:]

'123456789'

In [16]:
s[:3]

'012'

In [9]:
s[:]

'0123456789'

In [10]:
s[-1]

'9'

In [11]:
s[:-1]

'012345678'

In [12]:
s[::1]

'0123456789'

In [13]:
s[::2]

'02468'

In [14]:
s[::-1]

'9876543210'

### Exercise 16
Using Numpy notation, input the following mathematical expressions into Python.

$u=\left[\begin{array}{cccccc}
1 & 2 & 3 & 4 & 8 & 8\end{array}\right]$

$v=\left[\begin{array}{c}
1\\
2\\
3\\
4\\
8\\
9
\end{array}\right]$

$x=\left[\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right]$

$y=\left[\begin{array}{cc}
1 & 2\\
3 & 4
\end{array}\right]$

$z=\left[\begin{array}{cccc}
1 & 2 & 3 & 4\\
1 & 2 & 3 & 4\\
1 & 2 & 3 & 4
\end{array}\right]$

$w=\left[\begin{array}{cc}
x & x\\
y & y
\end{array}\right]$

Note: A column vector must be entered as a 2-dimensional array.


In [18]:
import numpy as np

In [3]:
u = np.array([1, 2, 3, 4 , 8, 8])
u

array([1, 2, 3, 4, 8, 8])

In [4]:
v = np.array([[1], [2], [3], [4], [8], [9]])
v

array([[1],
       [2],
       [3],
       [4],
       [8],
       [9]])

In [20]:
x = np.array([[1, 0], [0, 1]])
x

array([[1, 0],
       [0, 1]])

In [21]:
y = np.array([[1, 3], [2, 4]])
y

array([[1, 3],
       [2, 4]])

In [45]:
z = np.array([[1, 2, 3, 4], [1, 2, 3 ,4], [1, 2, 3, 4]])
z

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [23]:
xy = np.vstack((x, y))
xy


array([[1, 0],
       [0, 1],
       [1, 3],
       [2, 4]])

In [24]:
w = np.hstack((xy, xy))
w

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 3, 1, 3],
       [2, 4, 2, 4]])

### Exercise 17

-What command would select x from w?

-What command would select [x',y']' from w?

-What comand would select y from z?


In [33]:
w[:2, :2]


array([[1, 0],
       [0, 1]])

In [34]:
w[:2, 2:4]

array([[1, 0],
       [0, 1]])

In [36]:
np.transpose(x)

array([[1, 0],
       [0, 1]])

In [38]:
np.transpose(y)

array([[1, 2],
       [3, 4]])

In [42]:
xy_wide = np.hstack((np.transpose(x), np.transpose(y)))

In [43]:
wy_prime = np.transpose(xy_wide)
wy_prime

array([[1, 0],
       [0, 1],
       [1, 3],
       [2, 4]])

In [46]:
z[0, :]


array([1, 2, 3, 4])

In [47]:
np.reshape(z[0, :], [2,2])

array([[1, 2],
       [3, 4]])

### Exercise 18
- Create a one-dimentional array 
- Display the type of the array
- Display the shape of the array

In [22]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
type(b)

numpy.ndarray

In [24]:
b.shape

(10,)

In [29]:
f = np.empty(0)
f

array([], dtype=float64)

### EX18 
- Create a 2-dimensional array `y` with the shape 3x3

$y=\left[\begin{array}{ccc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right]$
         
- Display the shape of the array `y`
- Select the submatrix y1 and y2 as

$y1=\left[\begin{array}{cc}
1 & 2\\
4 & 5
\end{array}\right]$
          
$y2=\left[\begin{array}{cc}
5 & 6\\
8 & 9
\end{array}\right]$

- compute `y1 + y2`
- compute element-by-element mulitplication of `y1` and `y2`

In [2]:
import numpy as np
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y)
y.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [23]:
y1 = y[0:2, :2]
y1

array([[1, 2],
       [4, 5]])

In [21]:
y2 = y[1:3, 1:3]
y2

array([[5, 6],
       [8, 9]])

In [24]:
y1 + y2

array([[ 6,  8],
       [12, 14]])

In [25]:
y1 * y2

array([[ 5, 12],
       [32, 45]])

### EX19 
- generate a 3x3 2-d array with zero in all elements.

$y=\left[\begin{array}{ccc}
0.0 & 0.0 & 0.0\\
0.0 & 0.0 & 0.0\\
0.0 & 0.0 & 0.0
\end{array}\right]$

- replace the 1st row in `y` as a seqence of number from 1 to 3

- Extract a diagonal array: array([ 1.,  0.,  0.])

- Construct a new matrix with array([ 1.,  2.,  3.]) as diagonal array. The rest elements are zeros.

    array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
         

In [45]:
import numpy as np
y3 = np.zeros((3,3))
y3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
y3[:, 0] = 1, 2, 3
y3

array([[1., 0., 0.],
       [2., 0., 0.],
       [3., 0., 0.]])

In [47]:
y3[:, 0]
y3

array([[1., 0., 0.],
       [2., 0., 0.],
       [3., 0., 0.]])

In [48]:
np.diag(y3)


array([1., 0., 0.])

array([1., 0., 0.])

In [42]:
y4 = np.array([[1, 0 ,0], [0, 2, 0], [0, 0, 3]])
y4

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [48]:
np.diag(np.arange(1, 4))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])